name: Clojure Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    # run on mac for now until I compile the parser for linux.
    runs-on: macOS-latest
    # runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: install lein
      run: brew install leiningen
    - name: Install dependencies
      run: cd clojure; lein deps
    - name: Run tests
      run: cd clojure; lein test
