name: Linux build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup-graalvm-ce
      uses: rinx/setup-graalvm-ce@v0.0.5
      with:
        graalvm-version: "20.2.0"
        java-version: "java11"
        native-image: "true"
    # - name: setup-native-image
    #   run: |
    #     gu install native-image
    - name: run compile script
      run: |
        bin/compile

    - uses: actions/upload-artifact@v1
      with:
        name: firn-linux
        path: target/
